[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]
  included_files = ["netlify/functions/*"]

# ✅ No redirect for functions!
# This makes sure Stripe can hit your webhook directly.

[[redirects]]
  from = "http://datagaffer.com/*"
  to = "https://www.datagaffer.com/:splat"
  status = 301
  force = true