[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]
  included_files = ["netlify/functions/*"]

[build.environment]
  NODE_VERSION = "18"
